#Automatically generated by entry_gen.pl
package Qt4OnGtk;
use strict;
use warnings;
use Qt::QAction;
use Qt::QApplication;
use Qt::QHBoxLayout;
use Qt::QLineEdit;
use Qt::QList;
use Qt::QMenu;
use Qt::QMenuBar;
use Qt::QObject;
use Qt::QPushButton;
use Qt::QVBoxLayout;
use Qt::QWidget;
require Exporter;
our @ISA = qw(Exporter);
our @EXPORT = qw(QAction QApplication QHBoxLayout QLineEdit QList QMenu QMenuBar QObject QPushButton QVBoxLayout QWidget QtGlobalObject);
our $QtGlobalObject = Qt::QList->new();
sub QAction {
    my $o = Qt::QAction->new(@_);
    my $id = $QtGlobalObject->append($o);
    $o->_set_id($id);
    return $o;
}
sub QApplication {
    my $o = Qt::QApplication->new(@_);
    my $id = $QtGlobalObject->append($o);
    $o->_set_id($id);
    return $o;
}
sub QHBoxLayout {
    my $o = Qt::QHBoxLayout->new(@_);
    my $id = $QtGlobalObject->append($o);
    $o->_set_id($id);
    return $o;
}
sub QLineEdit {
    my $o = Qt::QLineEdit->new(@_);
    my $id = $QtGlobalObject->append($o);
    $o->_set_id($id);
    return $o;
}
sub QList {
    my $o = Qt::QList->new(@_);
    my $id = $QtGlobalObject->append($o);
    $o->_set_id($id);
    return $o;
}
sub QMenu {
    my $o = Qt::QMenu->new(@_);
    my $id = $QtGlobalObject->append($o);
    $o->_set_id($id);
    return $o;
}
sub QMenuBar {
    my $o = Qt::QMenuBar->new(@_);
    my $id = $QtGlobalObject->append($o);
    $o->_set_id($id);
    return $o;
}
sub QObject {
    my $o = Qt::QObject->new(@_);
    my $id = $QtGlobalObject->append($o);
    $o->_set_id($id);
    return $o;
}
sub QPushButton {
    my $o = Qt::QPushButton->new(@_);
    my $id = $QtGlobalObject->append($o);
    $o->_set_id($id);
    return $o;
}
sub QVBoxLayout {
    my $o = Qt::QVBoxLayout->new(@_);
    my $id = $QtGlobalObject->append($o);
    $o->_set_id($id);
    return $o;
}
sub QWidget {
    my $o = Qt::QWidget->new(@_);
    my $id = $QtGlobalObject->append($o);
    $o->_set_id($id);
    return $o;
}
package Qt;
use strict;
use warnings;
1;

